# Generated by Django 5.2.6 on 2025-09-05 00:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_id', models.IntegerField()),
                ('activity_type', models.CharField()),
                ('performed_at', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('municipality', models.TextField(choices=[('SUBACHOQUE', 'Subachoque'), ('ROSAL', 'Subachoque'), ('FACATATIVA', 'Subachoque'), ('MADRID', 'Madrid'), ('ZIPACON', 'Zipacon'), ('BOJACA', 'Bojaca'), ('MOSQUERA', 'Mosquera'), ('FUNZA', 'Funza'), ('COTA', 'Cota'), ('TENJO', 'Tenjo')], default='MOSQUERA')),
                ('crop_type', models.CharField(max_length=50)),
                ('area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HarvestBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('quantity_kg', models.FloatField()),
                ('quality_grade', models.CharField()),
                ('moisture_pct', models.IntegerField()),
                ('ph_soil', models.IntegerField(validators=[django.core.validators.MaxValueValidator(14)])),
                ('plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominio.fieldactivity')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField()),
                ('destination_city', models.CharField()),
                ('dispatched_at', models.DateField(auto_now_add=True)),
                ('quantity_kg', models.FloatField()),
                ('harvest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominio.harvestbatch')),
            ],
        ),
    ]
