# Generated by Django 5.2.6 on 2025-09-05 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundorder',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fieldactivity',
            name='plot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominio.plot'),
        ),
        migrations.AlterField(
            model_name='harvestbatch',
            name='plot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominio.plot'),
        ),
    ]
